scripts/element.py, scripts/oneapi.py, site-root/index.html, site-root/oneAPI/Elements/Level_Zero/Level_Zero_root.html, site-root/oneAPI/Elements/dpcpp/dpcpp_root.html, site-root/oneAPI/Elements/oneccl/oneccl_root.html, site-root/oneAPI/Elements/onedal/onedal_root.html, site-root/oneAPI/Elements/onednn/onednn_root.html, site-root/oneAPI/Elements/onedpl/onedpl_root.html, site-root/oneAPI/Elements/onemkl/onemkl_root.html, site-root/oneAPI/Elements/onetbb/onetbb_root.html, site-root/oneAPI/Elements/onevpl/onevpl_root.html, source/introduction.rst
Also better formatting of oneapi script messages
redirects for pages that have moved
=> Restructure production web site and publishing process

source/elements/oneDNN/include/dnnl.hpp
=> fix doxygen warnings for oneDNN

scripts/oneapi.py
get rid of site subdirectory so we can use absolute paths on staging
=> restructure s3

roadmap.rst
=> add oneDNN roadmap

roadmap.rst
Update with first version of roadmap for oneDAL
=> Update oneDAL roadmap

source/_templates/breadcrumbs.html, source/_templates/layout.html, source/conf/common_conf.py
Put the chapter title in the breadcrumbs. Done to make it more obvious which element version is being described.
=> changes for chapter versions

.github/workflows/main.yml, .gitignore, README.rst, scripts/oneapi.py
Resolves #76 
Disables S3 deploy when AWS secret is not available
Uploads the site as an artifact for inspection
=> test PR from fork

.github/workflows/main.yml, requirements.txt, scripts/install.sh, scripts/oneapi.py, source/conf/common_conf.py, source/elements/oneCCL/source/spec/collective_communication.rst, source/elements/oneVPL/source/VPL_workstreams.rst, source/elements/oneVPL/source/index.rst
Prefix the full_name's with oneAPI
Add support for spell checking
Resolves #87
=> Full names include oneAPI, add spellchecker

README.rst, source/elements/oneDAL/source/index.rst, source/elements/oneDAL/source/introduction.rst
In this change we removing extra oneAPI prefix in oneDAL spec and updating REAME file on remote repos use
=> Updating oneDAL full name use

README.rst, style-guide.rst
- The link in Style Guide wasn't working -- fixed it.
- Added a link to yaml file from README
=> Minor updates to README and Style Guide

source/elements/oneDAL/source/algorithms/decomposition/pca.rst, source/elements/oneDAL/source/bibliography.rst
https://rlnx.github.io/oneapi-spec/elements/oneDAL/source/algorithms/decomposition/pca.html
=> Add PCA algorithm

source/elements/oneVPL/source/VPL_device.rst, source/elements/oneVPL/source/VPL_device_context.rst, source/elements/oneVPL/source/VPL_parameters.rst, source/elements/oneVPL/source/VPL_workstreams.rst, source/elements/oneVPL/source/index.rst
Hi Robert,
I went through the spec and made some small changes to the wordings.  This should be the final version for the March release.
Thanks,
Peng.
=> Touch on wordings in preparation for the March release.

source/elements/dpcpp/source/index.rst
=> dpcpp update for 0.7

roadmap.rst
Updating oneDAL roadmap as we will focus more on overall structure definition and not new algorithms definition
=> updating oneDAL roadmap

source/elements/oneDAL/source/introduction.rst
In this change we reflect design decisions on intro page
=> Replacing service component with utils and misc in introduction page

roadmap.rst, source/elements/oneVPL/source/index.rst
Disclaimer added to oneVPL spec and roadmap to set expectations due to some oneVPL direction changes.
=> oneVPL: add revision disclaimer

source/elements/oneDAL/source/common_interface/error_handling.rst
=> error handling

scripts/oneapi.py, source/elements/oneDAL/source/introduction.rst, source/elements/oneVPL/source/index.rst
DAL page had some improper indentation, causing warnings.
While I was fixing it, I did the recommended indentation/wrapping for the entire page.
=> fix some formatting issues

scripts/oneapi.py, site-root/versions/0.6.0/oneL0/index.html, site-root/versions/0.7/oneL0/index.html, site-root/versions/latest/oneL0/index.html
* Delete code to manage separate l0 tarball
* Add redirects for old l0 location
* When syncing staging to prod, don't delete missing files so level zero can skip staging when publishing
=> Level Zero cleanup

source/_static/custom.css
https://github.com/readthedocs/sphinx_rtd_theme/issues/647
This probably requires an ack from owners of other parts of the spec.
=> Work around spacing problems in C++ function signatures

source/elements/oneDNN/include/dnnl.hpp
https://github.com/sphinx-doc/sphinx/issues/7740
=> oneDNN: work around Sphinx type lookup bug

source/elements/oneVPL/source/Versioning.rst, source/elements/oneVPL/source/index.rst
- Move Versioning content to new page
- Update toctree: remove hidden, add titlesonly, add new
Versioning page
Signed-off-by: Kristal Dale <kristal.dale@intel.com>
=> Update toctree to fix nav issues

source/elements/oneDAL/dalapi/extension.py, source/elements/oneDAL/include/oneapi/dal/knn.hpp, source/elements/oneDAL/include/oneapi/dal/table.hpp, source/elements/oneDAL/include/oneapi/dal/train.hpp, source/elements/oneDAL/include/onedal/table.hpp, source/elements/oneDAL/include/onedal/train.hpp, source/elements/oneDAL/source/algorithms/clustering/kmeans.rst, source/elements/oneDAL/source/algorithms/decomposition/pca.rst, source/elements/oneDAL/source/algorithms/nearest_neighbors/knn_classification.rst, source/elements/oneDAL/source/common_interface/error_handling.rst, source/elements/oneDAL/source/data_management/tables.rst, source/elements/oneDAL/source/programming_model/algorithm_anatomy.rst
- include directory path changed from `include\onedal` to `include\oneapi\dal`
- namespace `onedal` changed to `oneapi::dal`
=> [DAL] Changed include paths, namespace name updated

source/elements/oneDAL/include/oneapi/dal/kmeans_init.hpp, source/elements/oneDAL/source/algorithms/clustering/index.rst, source/elements/oneDAL/source/algorithms/clustering/kmeans_init.rst
oneDAL kmeans initialization algorithm
=> oneDAL kmeans initialization algorithm

source/elements/oneDAL/source/common_interface/error_handling.rst
=> oneDAL error handling improvements 

source/elements/oneDAL/include/oneapi/dal/kmeans_init.hpp, source/elements/oneDAL/source/algorithms/clustering/kmeans_init.rst
- kmeans_init::task
- build failure fix 
- other minor changes
=> oneDAL kmeans_init hot fix

doc/core-teams.rst, source/versions.rst
1. Add release notes for 1.0
2. Add oneMKL Core team members
=> oneMKL: add release notes and update core team

source/contributors.rst
I want to add oneMKL developers who actively contributed to oneMKL spec.
=> contributors: add oneMKL contributors

source/elements/oneTBB/source/configuration/version_information.rst
Add information about TBB_SPEC_VERSION macro. 
@aelizaro, @andreynv, can you please review.
=> Add TBB_SPEC_VERSION macro description

source/elements/oneTBB/source/index.rst, source/elements/oneTBB/source/info_namespace.rst, source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
This patch contains the oneTBB NUMA support API specification.
@akukanov, @alexey-katranov, @aleksei-fedotov please review if possible.
=> OneTBB NUMA support API spec

oneapi-doc.json, source/conf/common_conf.py, source/elements/oneVPL/include/onevpl/mfxcommon.h, source/elements/oneVPL/include/onevpl/mfxdefs.h, source/elements/oneVPL/include/onevpl/mfxdispatcherprefixedfunctions.h, source/elements/oneVPL/include/onevpl/mfxstructures.h, source/elements/oneVPL/include/onevpl/mfxvideo.h, source/elements/oneVPL/source/API_ref/VPL_defines.rst, source/elements/oneVPL/source/API_ref/VPL_disp_api_struct.rst, source/elements/oneVPL/source/API_ref/VPL_enums.rst, source/elements/oneVPL/source/API_ref/VPL_func_mem.rst, source/elements/oneVPL/source/API_ref/VPL_func_vid_decode_vpp.rst, source/elements/oneVPL/source/API_ref/VPL_func_vid_vpp.rst, source/elements/oneVPL/source/API_ref/VPL_functions.rst, source/elements/oneVPL/source/API_ref/VPL_structs.rst, source/elements/oneVPL/source/API_ref/VPL_structs_cross_component.rst, source/elements/oneVPL/source/API_ref/VPL_structs_decode.rst, source/elements/oneVPL/source/API_ref/VPL_structs_decode_vpp.rst, source/elements/oneVPL/source/VPL_summary.rst, source/elements/oneVPL/source/Versioning.rst, source/elements/oneVPL/source/appendix/VPL_intel_media_sdk.rst, source/elements/oneVPL/source/architecture/VPL_decoding_vpp.rst, source/elements/oneVPL/source/architecture/index.rst, source/elements/oneVPL/source/index.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_decoding.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_frame.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_mem.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_session.rst, source/elements/oneVPL/source/snippets/prg_decoding.c, source/elements/oneVPL/source/snippets/prg_decoding_vpp.c
Also spec version alighment with API verrsion.
=> oneVPL 2.1 API version release

.github/workflows/ci.yml, .pre-commit-config.yaml, ubuntu-packages.txt
Stop using container, use cached python
=> simplify CI

source/elements/oneART/source/index.rst
=> change rendering to ray tracing

oneapi-doc.json, source/conf.py, source/conf/element_conf.py, source/elements/oneART/source/acknowledgment.rst, source/elements/oneART/source/appendices.rst, source/elements/oneART/source/component-libraries.rst, source/elements/oneART/source/conf.py, source/elements/oneART/source/embree.rst, source/elements/oneART/source/index.rst, source/elements/oneART/source/ispc.rst, source/elements/oneART/source/nested-index.rst, source/elements/oneART/source/oidn.rst, source/elements/oneART/source/openvkl.rst, source/elements/oneART/source/ospray-hydra-plugin.rst, source/elements/oneART/source/ospray-studio.rst, source/elements/oneART/source/ospray.rst, source/elements/oneART/source/overview.inc.rst, source/elements/oneART/source/versions.rst, source/index.rst
@dmnemshi : Please look over text, but not formatting changes
=> Changes for oneART publishing

CONTRIBUTING.rst
=> Remove style guide link

source/conf/common_conf.py
=> changes for sphinx4

source/elements/oneMKL/source/conf.py
=> fix onemkl standalone config

source/conf.py, source/conf/element_conf.py, source/elements/oneDAL/dalapi/directives.py, source/elements/oneDAL/dalapi/doxypy/__init__.py, source/elements/oneDAL/dalapi/doxypy/builder.py, source/elements/oneDAL/dalapi/doxypy/index.py, source/elements/oneDAL/dalapi/doxypy/loader.py, source/elements/oneDAL/dalapi/doxypy/parser/compound.py, source/elements/oneDAL/dalapi/doxypy/parser/index.py, source/elements/oneDAL/dalapi/extension.py, source/elements/oneDAL/dalapi/generator.py, source/elements/oneDAL/dalapi/transformers.py, source/elements/oneDAL/dalapi/utils.py, source/elements/oneDAL/make.bat, source/elements/oneDAL/source/conf.py
Dalapi tool source code is synchronized with the master of oneDAL repo.
=> [oneDAL] Update dalapi tool

source/elements/oneDAL/include/oneapi/dal/array.hpp, source/elements/oneDAL/source/data_management/array.rst
- Change wording for some array methods
- Update data ownership requirements
- Add implementation notes 
Link to generated HTML: https://rlnx.github.io/oneapi-spec/bugfix-1.2-array-new/data_management/array.html
=> [oneDAL] Update array spec

source/elements/oneTBB/source/flow_graph/limiter_node_cls.rst
Signed-off-by: ilya.mishin <ilya.mishin@intel.com>
=> [oneTBB] Improve limiter_node decrementer spec

source/elements/oneTBB/source/containers/concurrent_multiset_cls.rst, source/elements/oneTBB/source/containers/concurrent_set_cls.rst
- fixed wording for concurrent [ordered] set and multiset containers
=> [oneTBB] fixed wording for ordered set/multiset description

source/elements/oneTBB/source/algorithms.rst, source/elements/oneTBB/source/algorithms/functions/collaborative_call_once_func.rst, source/elements/oneTBB/source/algorithms/functions/collaborative_once_flag_cls.rst
Notify: @alexey-katranov @alexandraepan @pavelkumbrasev 
Signed-off-by: Ilya Isaev <ilya.isaev@intel.com>
=> [oneTBB] collaborative_call_once algorithm

source/elements/oneTBB/source/algorithms/functions/collaborative_call_once_func.rst
Signed-off-by: Ilya Isaev <ilya.isaev@intel.com>
Notify: @omalyshe @alexey-katranov
=> [oneTBB] Fix code example in collaborative_call_once

source/elements/oneMKL/source/domains/blas/gemm.rst, source/elements/oneMKL/source/domains/blas/gemm_batch.rst, source/elements/oneMKL/source/domains/blas/gemm_bias.rst
This PR is fixing bugs for ldc parameter.
=> [oneMKL: BLAS] bug fix for ldc parameter

source/elements/oneMKL/source/domains/blas/her.rst, source/elements/oneMKL/source/domains/blas/hpr.rst
This PR is fixing scalar types in her/hpr.
=> [oneMKL-BLAS] Fix her/hpr scalar type

source/elements/oneMKL/source/domains/blas/rotmg.rst
This PR is fixing a bug related to how 5th arguments is passed in rotmg API.
=> [oneMKL][BLAS] Fix rotmg documentation

source/elements/oneDPL/source/sycl_kernels_api.rst
The initial version of a specification for pseudo-random number generation API, based on the draft prepared by Pavel Dyakov.
=> [oneDPL] Add RNG functionality

source/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.rst
Extend the description of the task_group.
=> [oneTBB] Update task_group_cls.rst

source/elements/oneTBB/source/algorithms/functions/parallel_pipeline_func.rst
Fix the name from filter::serial to filter::serial_in_order and from filter::parallel to filter_mode::parallel in the code samples.
=> [oneTBB]: Update parallel_pipeline_func.rst

oneapi-doc.json, source/elements/oneVPL/include/vpl/mfxadapter.h, source/elements/oneVPL/include/vpl/mfxcommon.h, source/elements/oneVPL/include/vpl/mfxdefs.h, source/elements/oneVPL/include/vpl/mfxdispatcher.h, source/elements/oneVPL/include/vpl/mfxstructures.h, source/elements/oneVPL/include/vpl/mfxvideo++.h, source/elements/oneVPL/source/API_ref/VPL_disp_api_enum.rst, source/elements/oneVPL/source/API_ref/VPL_disp_api_struct.rst, source/elements/oneVPL/source/API_ref/VPL_enums.rst, source/elements/oneVPL/source/API_ref/VPL_structs_cross_component.rst, source/elements/oneVPL/source/API_ref/VPL_structs_decode_vpp.rst, source/elements/oneVPL/source/API_ref/VPL_structs_impl_manage.rst, source/elements/oneVPL/source/API_ref/VPL_structs_vpp.rst, source/elements/oneVPL/source/Experimental.rst, source/elements/oneVPL/source/VPL_change_log.rst, source/elements/oneVPL/source/VPL_deprecation.rst, source/elements/oneVPL/source/VPL_intel_media_sdk.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_hw.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_session.rst, source/elements/oneVPL/source/programming_guide/VPL_prg_vpp.rst, source/elements/oneVPL/source/snippets/prg_disp.c, source/elements/oneVPL/source/snippets/prg_vpp.c, source/elements/oneVPL/source/spelling_wordlist_vpl.txt
=> OneVPL v2.9

source/elements/oneDNN/source/data_model/data_types/int8.rst
This PR fixes a single line in `int8.rst`
Signed-off-by: Sanggyu Lee [sanggyu523@naver.com](mailto:sanggyu523@naver.com)
=> Fix typo in int8.rst

source/elements/oneMKL/source/domains/blas/gemv_batch.rst
=> [oneMKL] fix gemv_batch op

source/notices.rst
Addresses https://github.com/uxlfoundation/operations/issues/76
=> Update notice for UXL

source/_static/custom.js
Remove TMS. It was used for analytics when spec was part of intel
=> remove tms
