- .gitlab-ci.yml
- requirements.txt
- scripts/install.sh
- scripts/oneapi.py
Add options to make latex silent and stop on first error instead of waiting for input. For some errors, latex will emit an error and wait for a response to the terminal. This caused CI system to hang. Requires sphinx 2.4.0, but earlier versions of sphinx will ignore the extra options.
> make latex silent and stop on error

- source/elements/oneTBB/source/configuration/feature_macros.rst
With the switch to C++11, this macro deprecated and will be removed from oneTBB
> Remove TBB_USE_CAPTURED_EXCEPTION

- source/elements/l0/source/index.rst
- source/elements/oneDAL/source/index.rst
- source/elements/oneMKL/source/index.rst
Eliminate relative external links because they will not work in the PDF.
> make external links absolute

- source/conf.py
- source/index.rst
- source/introduction.rst
- source/versions.rst
The place to download pdf and older versions of the spec is not apparent. I made it a separate section so it will appear near the bottom of the TOC in the left pane.
> make versions easier to find

- source/elements/oneCCL/source/introduction.rst
oneCCL moved to another repository. The redirects from the old repo are enabled, but the links should be updated at some point.
> Update links to oneCCL repo

- source/elements/oneDNN/include/dnnl.hpp
- source/elements/oneDNN/source/api/engine.rst
- source/elements/oneDNN/source/api/memory.rst
- source/elements/oneDNN/source/api/primitives.rst
- source/elements/oneDNN/source/api/primitives/attributes.rst
- source/elements/oneDNN/source/api/primitives/batch_normalization.rst
- source/elements/oneDNN/source/api/primitives/binary.rst
- source/elements/oneDNN/source/api/primitives/common.rst
- source/elements/oneDNN/source/api/primitives/concat.rst
- source/elements/oneDNN/source/api/primitives/convolution.rst
- source/elements/oneDNN/source/api/primitives/deconvolution.rst
- source/elements/oneDNN/source/api/primitives/eltwise.rst
- source/elements/oneDNN/source/api/primitives/inner_product.rst
- source/elements/oneDNN/source/api/primitives/layer_normalization.rst
- source/elements/oneDNN/source/api/primitives/logsoftmax.rst
- source/elements/oneDNN/source/api/primitives/lrn.rst
- source/elements/oneDNN/source/api/primitives/pooling.rst
- source/elements/oneDNN/source/api/primitives/reorder.rst
- source/elements/oneDNN/source/api/primitives/resampling.rst
- source/elements/oneDNN/source/api/primitives/rnn.rst
- source/elements/oneDNN/source/api/primitives/shuffle.rst
- source/elements/oneDNN/source/api/primitives/softmax.rst
- source/elements/oneDNN/source/api/primitives/sum.rst
- source/elements/oneDNN/source/api/stream.rst
- source/elements/oneDNN/source/api/utilities.rst
- source/elements/oneDNN/source/index.rst
Get rid of `doxygenindex` and split documentation into groups manually.
Co-authored-by: Ben Fitch <benjamin.fitch@intel.com>
> start restructuring oneDNN spec

- source/conf/common_conf.py
- source/elements/oneDAL/source/programming_model/basic_usage_scenario.rst
https://github.com/adamtheturtle/sphinx-substitution-extensions released new plugin version which introduces [breaking change](https://github.com/adamtheturtle/sphinx-substitution-extensions/blob/master/CHANGELOG.rst#202005270). Their change affects our CI #146 #149. The change proposed here fixes it.
> Fix sphinx-substitution-extensions breaking change

- source/elements/oneDAL/Makefile
- source/elements/oneDAL/dalapi/extension.py
- source/elements/oneDAL/dalapi/roles.py
- source/elements/oneDAL/source/data_management/index.rst
- source/elements/oneDAL/source/glossary.rst
Fix #147 with the help of [custom Sphinx role](https://protips.readthedocs.io/link-roles.html):
```py
_term_ref_re = re.compile(r'(.+)<(.+)>', flags=re.DOTALL)
def capterm_role(name, rawtext, text, lineno, inliner, options={}, content=[]):
xref_role = roles.XRefRole(innernodeclass=nodes.inline,
warn_dangling=True)
term_match = _term_ref_re.match(text)
if term_match:
txt, ref = term_match.group(1), term_match.group(2)
else:
txt, ref = text, text
fixed_term = f'{txt.strip()} <{ref.strip().capitalize()}>'
return xref_role('std:term', rawtext, fixed_term, lineno, inliner, options, content)
```
Results:
- The [produced output](https://rlnx.github.io/oneapi-spec/glossary.html) does not contain capitalized references.
- Sphinx does not generate warnings during the build.
- Less code: …
> [DAL] Fix term warnings

- source/elements/oneDAL/dalapi/extension.py
- source/elements/oneDAL/dalapi/roles.py
- source/elements/oneDAL/source/algorithms/nearest_neighbors/knn_classification.rst
- source/elements/oneDAL/source/data_management/accessors.rst
- source/elements/oneDAL/source/data_management/index.rst
- source/elements/oneDAL/source/data_management/table_builders.rst
- source/elements/oneDAL/source/data_management/tables.rst
- source/elements/oneDAL/source/introduction.rst
- source/elements/oneDAL/source/programming_model/algorithm_anatomy.rst
This PR proposes a new custom rule `txtref`. As a standard `ref` rule, this provides references to some locations in a document.
Consider next reference declaration:
```rst
:: _some_ref:
Some reference
```
- `:ref:'some_ref'` will result to the text after `some_ref` declaration: `Some reference`
- `txtref:'some_ref'` will result to `some ref` and points to the same destination as a `ref` clause
**Rules of `txtref` role** 
1. **:txtref:'some_text'** will create a link to `some_text` destination and results to the original text of the link with delimiter characters (`-` and `_`) replaced by spaces:
- :txtref:'some_text' -> some text
-  :txtref:'some-text' -> some text
- :txtref:'some_another-text' -> some another text
2. **:txtref:'Table_API'** will create a link to `Table_API` and results …
> [DAL] Lowercase references in the text

- source/elements/oneMKL/source/architecture/other_architecture.inc.rst
Based on feedback from [oneMKL/issues/34](https://github.com/oneapi-src/oneMKL/issues/34), updating MINOR to remove option of "deleting" apis.
> [oneMKL] Adjust Version scheme definition for clarity

- source/elements/oneVPL/include/onevpl/mfxdefs.h
- source/elements/oneVPL/include/onevpl/mfxstructures.h
Update legacy and current product names for oneVPL to be
compliant with product names DB guidelines.
Signed-off-by: Kristal Dale <kristal.dale@intel.com>
> Update oneVPL and Media SDK product names

- source/elements/oneDAL/dalapi/directives.py
- source/elements/oneDAL/dalapi/extension.py
- source/elements/oneDAL/include/oneapi/dal/kmeans.hpp
- source/elements/oneDAL/include/oneapi/dal/knn.hpp
- source/elements/oneDAL/include/oneapi/dal/pca.hpp
- source/elements/oneDAL/make.bat
- source/elements/oneDAL/source/algorithms/clustering/index.rst
- source/elements/oneDAL/source/algorithms/clustering/kmeans.rst
- source/elements/oneDAL/source/algorithms/decomposition/index.rst
- source/elements/oneDAL/source/algorithms/decomposition/pca.rst
- source/elements/oneDAL/source/algorithms/index.rst
- source/elements/oneDAL/source/algorithms/nearest_neighbors/index.rst
- source/elements/oneDAL/source/algorithms/nearest_neighbors/knn_classification.rst
- source/elements/oneDAL/source/bibliography.rst
- source/elements/oneDAL/source/glossary.rst
Changes:
- Port all API definitions from raw RST to the "Tool"
- Add missing sections about inference
- Add missing examples 
- Add `Task` to template parameters for all algorithms
**Links:**
- K-Means: https://rlnx.github.io/oneapi-spec/task-api/algorithms/clustering/kmeans.html
- kNN: https://rlnx.github.io/oneapi-spec/task-api/algorithms/nearest_neighbors/knn_classification.html
- PCA: https://rlnx.github.io/oneapi-spec/task-api/algorithms/decomposition/pca.html
> [DAL] Add task to template parameters for all algos

- source/elements/oneDAL/dalapi/directives.py
- source/elements/oneDAL/dalapi/generator.py
Fix of #218 
The issue is that dalapi generates fake class member for properties, which can conflict with other names in the class.
For example, in the ``homogen_table``:
```cpp
class homogen_table {
public:
static int64_t kind();
public:
int64_t get_kind();
};
```
For ``get_kind()`` the ``kind`` property is generated, which conflicts with static function.
Here I implemented a fix proposed by @rscohn2 by placing generated property symbol inside fake namespace. It does not affect the doc rendering, but affect the reference name of the symbol in html file.
> [DAL] Build warning fix

- source/elements/oneDAL/include/oneapi/dal/table/common.hpp
- source/elements/oneDAL/source/data_management/accessor/column.rst
- source/elements/oneDAL/source/data_management/accessor/row.rst
- source/elements/oneDAL/source/data_management/array.rst
- source/elements/oneDAL/source/data_management/csv_data_source.rst
- source/elements/oneDAL/source/data_management/data_sources.rst
- source/elements/oneDAL/source/data_management/index.rst
- source/elements/oneDAL/source/data_management/table/homogen.rst
- source/elements/oneDAL/source/data_management/tables.rst
* Common section with table declarations renamed to "tables". It has a section "table" describing common table interface, that's why I decided to rename the parent topic. 
* Some references to table types fixed
* Managed how to make default metadata property value to appear
* Data sources: namespace fixes
* Common phrase in programming interface sections is used.
> [DAL] stylistic corrections in data management layer

- source/elements/oneCCL/source/spec/generic_workflow.rst
Removed reference on CCL namespace in example.
The exact namespace name is not defined by spec.
> oneCCL: correct example

- source/elements/oneTBB/source/configuration/namespaces.rst
Add a description of the oneapi top level namespace and its relation to the ::tbb namespace.
> oneTBB: add the oneapi::tbb namespace description

- source/elements/oneDNN/include/dnnl.hpp
- source/elements/oneDNN/include/dnnl_sycl.hpp
- source/elements/oneDNN/source/example.cpp
A minor fix before we release to aling the specs with the latest state of the oneDNN opensource project.
> oneDNN: adjust memory allocation kind

- source/elements/oneTBB/source/index.rst
- source/elements/oneTBB/source/info_namespace.rst
- source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
* Initial version of the NUMA support documentation
* Change the line ends symbols for inside namespace page (CLRF -> LF)
* Apply review comments
* Apply suggestions from code review
Co-authored-by: Aleksei Fedotov <15153785+aleksei-fedotov@users.noreply.github.com>
* Wrap task_arena mention into ``
Co-authored-by: Aleksei Fedotov <15153785+aleksei-fedotov@users.noreply.github.com>
> OneTBB NUMA support API spec (#238)

- source/elements/oneTBB/source/nested-aux-interfaces.rst
@ivankochin: Please check this
standalone tbb spec (aux-interfaces.rst) and integrated (nested-aux-interfaces.rst) have separate top-level TOC. Add a missing file.
> add reference to info_namespace for tbb

- source/elements/oneMKL/source/domains/dft/compute_backward.rst
- source/elements/oneMKL/source/domains/dft/compute_forward.rst
updates template argument order in compute_forward and compute_backward apis.
> [oneMKL][DFT] switch template arguments order and add descriptor -> descriptor_type

- source/elements/oneCCL/source/spec/collective_operations.rst
- source/elements/oneCCL/source/spec/datatypes.rst
- source/elements/oneCCL/source/spec/error_handling.rst
- source/elements/oneCCL/source/spec/generic_workflow.rst
- source/elements/oneCCL/source/spec/main_objects.rst
- source/elements/oneCCL/source/spec/operation_attributes.rst
- source/elements/oneCCL/source/spec/operation_progress.rst
Mark FP16, input events and multiple ranks per process as optional
Replace rank datatype size_t -> int
Remove excessive const qualifiers
Remove default stream for communication operations
> oneCCL: apply corrections for v1.0

- CONTRIBUTING.rst
- README.rst
- General editorial/capitalization/readability edits
- Standardize capitalization in section headings
- Add local TOC for easier navigation
- Add contribute and license section to README
- Consolidate guidance for contributing (re editing, etc) to
CONTRIBUTING
- Move build instructions into 'Build the Specification'
section
- Some reorganization of content for consistency and
readability
Signed-off-by: Kristal Dale <kristal.dale@intel.com>
> Update README AND CONTRIBUTING

- source/elements/oneMKL/source/architecture/execution_model.inc.rst
Small clarification to disallow calling a oneMKL computational routine with a dependency on a future oneMKL API call (can be done in a few ways). This allows implementations to claim state and resources in an asynchronous routine at the time of the first call without worrying about deadlocks.
> Disallow antidependencies between oneMKL APIs

- source/elements/oneDPL/source/common.rst
A specification patch that fixes https://github.com/oneapi-src/oneAPI-spec/issues/304
> Remove namespace oneapi::std from oneDPL

- source/elements/oneVPL/include/vpl/mfxcommon.h
- source/elements/oneVPL/source/API_ref/VPL_enums.rst
- source/elements/oneVPL/source/VPL_change_log.rst
Important: needs to merged after watermark turning off for prod env.
This release brings:
* Encoding in Hyper mode.
* New product names for platforms:
* Code name Rocket Lake,
* Code name Alder Lake S,
* Code name Alder Lake P,
* Code name for Arctic Sound P.
* For spec version 2.3.1 MFX_PLATFORM_XEHP alias was added
* mfx.h header file is added which includes all header files.
* Added deprecation messages (deprecation macro) to the functions MFXInit and
MFXInitEx functions definition.
> oneVPL 2.3.1 release

- oneapi-doc.json
- source/elements/oneVPL/include/vpl/mfxcommon.h
- source/elements/oneVPL/source/API_ref/VPL_enums.rst
- source/elements/oneVPL/source/VPL_change_log.rst
* Encoding in Hyper mode.
* New product names for platforms:
* Code name Rocket Lake,
* Code name Alder Lake S,
* Code name Alder Lake P,
* Code name for Arctic Sound P.
* For spec version 2.3.1 MFX_PLATFORM_XEHP_SDV alias was added
* mfx.h header file is added which includes all header files.
* Added deprecation messages (deprecation macro) to the functions MFXInit and
MFXInitEx functions definition.
> oneVPL 2.3.1 (u) release

- oneapi-doc.json
- source/elements/oneVPL/include/vpl/mfxcommon.h
- source/elements/oneVPL/include/vpl/mfxdefs.h
- source/elements/oneVPL/include/vpl/mfxdispatcher.h
- source/elements/oneVPL/include/vpl/mfxstructures.h
- source/elements/oneVPL/source/API_ref/VPL_enums.rst
- source/elements/oneVPL/source/API_ref/VPL_structs_cross_component.rst
- source/elements/oneVPL/source/API_ref/VPL_structs_encode.rst
- source/elements/oneVPL/source/API_ref/VPL_structs_vpp.rst
- source/elements/oneVPL/source/VPL_change_log.rst
- source/elements/oneVPL/source/appendix/VPL_apnds_e.rst
- source/elements/oneVPL/source/index.rst
- source/elements/oneVPL/source/programming_guide/VPL_prg_decoding.rst
- source/elements/oneVPL/source/programming_guide/VPL_prg_encoding.rst
- source/elements/oneVPL/source/programming_guide/VPL_prg_session.rst
- source/elements/oneVPL/source/programming_guide/VPL_prg_transcoding.rst
- source/elements/oneVPL/source/programming_guide/VPL_prg_vpp.rst
- source/elements/oneVPL/source/snippets/appnd_b.c
- source/elements/oneVPL/source/snippets/appnd_e.c
- source/elements/oneVPL/source/snippets/appnd_f.c
- source/elements/oneVPL/source/snippets/prg_decoding.c
- source/elements/oneVPL/source/snippets/prg_decoding_vpp.c
- source/elements/oneVPL/source/snippets/prg_disp.c
- source/elements/oneVPL/source/snippets/prg_encoding.c
- source/elements/oneVPL/source/snippets/prg_err.c
- source/elements/oneVPL/source/snippets/prg_hw.cpp
- source/elements/oneVPL/source/snippets/prg_mem.c
- source/elements/oneVPL/source/snippets/prg_session.cpp
- source/elements/oneVPL/source/snippets/prg_transcoding.c
- source/elements/oneVPL/source/snippets/prg_vpp.c
* Added ability to retrieve path to the shared library with the implementation.
* Added 3DLUT (Three-Dimensional Look Up Table) filter in VPP.
* Added mfxGUID structure to specify Globally Unique Identifiers (GUIDs).
* Added QueryInterface function to mfxFrameSurfaceInterface.
* Added AdaptiveRef and alias for ExtBrcAdaptiveLTR.
* Added MFX_FOURCC_BGRP FourCC for Planar BGR format.
* Environmental variables to control dispatcher's logger.
> oneVPL Spec update to version 2.4

- .github/workflows/ci.yml
This commit avoids making the repository grow in size too fast by
overwriting the gh-pages branch on every build. This commit is not
enough in itself. To decrease the repository size, we also need to do
something like cherry-pick the latest gh-pages into a new orphan branch,
then force-push this branch to gh-pages. Newly unreachable objects
should be slowly garbage-collected over time.
(Partially) Fixes #334.
> Amend and force-push to publish to GitHub Pages

- source/elements/oneDPL/source/extensions.rst
The specification of the vectorized search algorithms in the oneDPL extension API did not include the requirements for the comparator provided to the algorithm, nor the related requirement on the partitioning of the data that will be searched.  Adding a sentence to each of `binary_search`, `lower_bound`, and `upper_bound` to resolve this.
Signed-off-by: Timmie Smith timmie.smith@intel.com
> Add requirements for search algorithm comparator

- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_hash_map_cls.rst
- source/elements/oneTBB/source/containers/concurrent_hash_map_cls/construct_destroy_copy.rst
- source/elements/oneTBB/source/containers/concurrent_hash_map_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_map_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_multimap_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_multiset_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_priority_queue_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_set_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_unordered_map_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_unordered_multimap_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_unordered_multiset_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_unordered_set_cls/deduction_guides.rst
- source/elements/oneTBB/source/containers/concurrent_vector_cls/deduction_guides.rst
The change was done to clarify the deduction guides description, align it with the STL approach.
Signed-off-by: kboyarinov konstantin.boyarinov@intel.com
> [oneTBB] Changing description for containers deduction guides

- source/elements/oneTBB/source/named_requirements/algorithms/par_for_each_body.rst
Now the `parallel_for_each` algorithm body named requirements contain unclear and incorrect formulation. This patch fixes it and makes it more clear.
Signed-off-by: Kochin, Ivan <kochin.ivan@intel.com>
> [oneTBB] Rework the parallel_for_each algorithm requirements

- source/elements/oneTBB/source/algorithms/functions/parallel_reduce_func.rst
parallel_reduce spec contains incorrect link to ParallelReduceReduction named requirement
> [oneTBB] Fix link ParallelReduceReduction requirement

- source/elements/oneTBB/source/mutual_exclusion.rst
- source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
- source/elements/oneTBB/source/mutual_exclusion/rw_mutex_cls.rst
- source/elements/oneTBB/source/named_requirements/mutexes/mutex.rst
- source/elements/oneTBB/source/named_requirements/mutexes/rw_mutex.rst
Signed-off-by: pavelkumbrasev <pavel.kumbrasev@intel.com>
> [oneTBB] Add adaptive mutexes

- source/elements/oneTBB/source/deprecated/task_arena_attach_tag.rst
- source/elements/oneTBB/source/index.rst
- source/elements/oneTBB/source/nested-depr-interfaces.rst
- source/elements/oneTBB/source/nested-index.rst
- source/elements/oneTBB/source/task_scheduler.rst
- source/elements/oneTBB/source/task_scheduler/attach_tag_type.rst
- source/elements/oneTBB/source/task_scheduler/scheduling_controls/task_scheduler_handle_cls.rst
- source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
Add `task_scheduler_handle` description (preview implementation description: https://docs.oneapi.io/versions/latest/onetbb/reference/blocking_terminate.html). There are some changes releated to `get` (removed) and `release` (became a member function) methods.
Additionally, deprecated `task_arena::attach` and introduce `oneapi::tbb::attach`.
Notify: @kboyarinov @anton-potapov
> [oneTBB] Add task_scheduler_handle

- source/elements/oneTBB/source/flow_graph/graph_cls.rst
- source/elements/oneTBB/source/flow_graph/indexer_node_cls.rst
- source/elements/oneTBB/source/flow_graph/input_node_cls.rst
- source/elements/oneTBB/source/flow_graph/message_flow_graph_example.rst
- source/elements/oneTBB/source/flow_graph/multifunc_node_cls.rst
- source/elements/oneTBB/source/flow_graph/overwrite_node_cls.rst
- source/elements/oneTBB/source/flow_graph/priority_queue_node_cls.rst
- source/elements/oneTBB/source/flow_graph/split_node_cls.rst
Signed-off-by: ilya.mishin <ilya.mishin@intel.com>
> [oneTBB] Fix flow graph inaccuracies 

- source/elements/oneTBB/source/flow_graph/graph_cls.rst
- source/elements/oneTBB/source/flow_graph/indexer_node_cls.rst
- source/elements/oneTBB/source/flow_graph/input_node_cls.rst
- source/elements/oneTBB/source/flow_graph/message_flow_graph_example.rst
- source/elements/oneTBB/source/flow_graph/multifunc_node_cls.rst
- source/elements/oneTBB/source/flow_graph/overwrite_node_cls.rst
- source/elements/oneTBB/source/flow_graph/priority_queue_node_cls.rst
- source/elements/oneTBB/source/flow_graph/split_node_cls.rst
In PR https://github.com/oneapi-src/oneAPI-spec/pull/369 copyright  years have not been changed.
In this request copyright year changed 2020->2021
Signed-off-by: ilya.mishin <ilya.mishin@intel.com>
> [oneTBB] Fix flow graph copyright year

- source/elements/oneTBB/source/algorithms/functions/parallel_deterministic_reduce_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_for_each_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_for_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_invoke_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_pipeline_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_reduce_func.rst
- source/elements/oneTBB/source/flow_graph/graph_cls.rst
- fixed name and description of ``task_grtoup_context`` in the several places 
Signed-off-by: Anton Potapov <anton.potapov@intel.com>
> [oneTBB] - fix task_group_context argument description

- source/elements/oneTBB/source/algorithms/functions/collaborative_call_once_func.rst
- source/elements/oneTBB/source/algorithms/functions/parallel_invoke_func.rst
- source/elements/oneTBB/source/named_requirements/algorithms/par_for_each_body.rst
- source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
- source/elements/oneTBB/source/task_scheduler/task_arena/this_task_arena_ns.rst
- source/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.rst
- source/elements/oneTBB/source/thread_local_storage/combinable_cls.rst
- source/elements/oneTBB/source/thread_local_storage/enumerable_thread_specific_cls/combining.rst
Fixed wording on user defined function to match ISO c++ standard named requirement `[function.objects]`
@alexandraepan could you please take a look ?
> [oneTBB] Function object iso cpp requirements 

- source/elements/oneMKL/source/architecture/api_design.inc.rst
- source/elements/oneMKL/source/domains/spblas/gemm.rst
**Goal:**
for `sparse::gemm()` functionality, which is sparse matrix-dense matrix product, support dense matrix storage layout of `column-major` as well as `row-major`.
**Details:**
Currently, there is no parameter related to dense matrix storage layout in `spares::gemm()` API and assumes the dense matrices are in `row-major` matrix storage layout.  In this PR, I propose to support below features:
- support `layout` of dense matrices of matrix `B` and `C` for both `row-major` and `column-major`.
- add matrix operation parameter for `B` matrix, so that we can handle `transposed` case of matrix `B` as well as `non-transpose` case.
- introduce a new enum class for `layout` information as `oneapi::mkl::layout`, which consists of `row_major` and `col_major`. 
**Motivation:**
As I mentioned …
> [oneMKL][spblas] updated sparse::gemm routines spec, which adds supporting matrix storage layout

- source/elements/element_list.rst
- source/elements/oneART/source/conf.py
- source/elements/oneART/source/embree-spec.rst
- source/elements/oneART/source/index.rst
- source/elements/oneART/source/nested-index.rst
- source/elements/oneART/source/oidn-spec.rst
- source/elements/oneART/source/openvkl-spec.rst
- source/elements/oneART/source/ospray-spec.rst
- source/elements/oneART/source/overview.inc.rst
Update component specifications to include latest feature content.
> oneART component updates

- source/conf.py
- source/conf/common_conf.py
- source/elements/dpcpp/source/conf.py
- source/elements/dpcpp/source/index.rst
Update DPC++ specification for 1.1 release.  Primarily addition of new extensions, and removal of previous extensions that have been successfully folded into the SYCL 2020 specification.
Signed-off-by: Michael Kinsner <michael.kinsner@intel.com>
> Update DPC++ specification for 1.1 release

- .github/workflows/ci.yml
- source/elements/oneMKL/source/domains/blas/axpby.rst
- source/elements/oneMKL/source/domains/blas/blas-like-extensions.rst
- source/elements/oneMKL/source/domains/blas/copy_batch.rst
- source/elements/oneMKL/source/domains/blas/dgmm_batch.rst
- source/elements/oneMKL/source/domains/blas/gemm.rst
- source/elements/oneMKL/source/domains/blas/gemm_batch.rst
- source/elements/oneMKL/source/domains/blas/gemv.rst
- source/elements/oneMKL/source/domains/blas/gemv_batch.rst
- source/elements/oneMKL/source/domains/blas/syrk_batch.rst
- source/elements/oneMKL/source/domains/blas/trsm_batch.rst
Adding BLAS APIs now in oneMKL product to the specification.
> [oneMKL] Add BLAS APIs

- source/elements/oneTBB/source/task_scheduler/scheduling_controls/global_control_cls.rst
- thread wrapper classes (std::thread like) were removed during the revamp
> [oneTBB] remove thread wrapper classes mentions

- source/elements/oneTBB/source/algorithms/functions/parallel_sort_func.rst
The `oneapi::tbb::parallel_sort()` algorithm may use `std::sort()`, so it has additional `MoveAssignable` requirements from [moveassignable] and the `MoveConstructible` requirements from [moveconstructible] ISO C++ Standard sections.
Signed-off-by: Kochin Ivan <kochin.ivan@intel.com>
> [oneTBB] Add Move semantic requirements to the parallel_sort algorithm

- source/elements/oneTBB/source/info_namespace.rst
- source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
It was decided the Core Types preference API can be added to the oneTBB spec reference. This interface allows setting the preferred core type for the threads within a certain arena on the system with hybrid processors.
> [oneTBB] Add the Core Types preference API to the spec

- source/elements/oneTBB/source/algorithms/functions/collaborative_once_flag_cls.rst
`Member functions` section contains only default constructor. This means that `collaborative_once_flag` can't be copied or assigned. But there is missed declaration of deleted `operator=`. This patch fix it.
Notify: @alexey-katranov 
Signed-off-by: Ilya Isaev <ilya.isaev@intel.com>
> [oneTBB] Add missed deleted assignment operator

- releases/index.rst
> update oneDNN Graph with latest release

- source/elements/oneTBB/source/flow_graph/examples/overwrite_node_cls.cpp
Update `oneapi::tbb::flow::overwrite_node` example for using `oneapi::tbb::flow::input_node` instead of `oneapi::tbb::flow::source_node`
Fixes #402.
@anton-potapov @aleksei-fedotov @alexandraepan
> oneapi::tbb::flow::overwrite_node example use undeclared class #402

- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls.rst
- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls/construct_destroy_copy.rst
- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls/non_member_binary_comparisons.rst
- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls/non_member_swap.rst
- source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls/unsafe_member_functions.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls/construct_destroy_copy.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls/non_member_binary_comparisons.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls/non_member_swap.rst
- source/elements/oneTBB/source/containers/concurrent_queue_cls/unsafe_member_functions.rst
For some unknown reason  `concurrent_queue` and  `concurrent_bounded_queue` differ significantly with `concurrent_priority_queue` in the part of helper methods.  This patch tries to align this.
- added :
- `operator=` with overloads
- `assign` method
- `swap`
- `operator==`
- `operator!=`
> Align interface of concurrent_queue and concurrent_bounded_queue with concurrent_priority_queue

- source/elements/oneMKL/source/domains/lapack/orgqr.rst
- source/elements/oneMKL/source/domains/lapack/orgqr_batch.rst
Changes made: Add constraint 'n <= m'
Rationale: The existing specification erroneously omits this constraint
> [oneMKL][LAPACK] Add missing constraint on parameter 'n' for orgqr functions

- source/elements/oneTBB/source/algorithms/functions/parallel_reduce_func.rst
> Fix typo in the parallel_reduce

- source/elements/oneMKL/source/domains/blas/axpy.rst
- source/elements/oneMKL/source/domains/blas/dot.rst
- source/elements/oneMKL/source/domains/blas/nrm2.rst
- source/elements/oneMKL/source/domains/blas/rot.rst
- source/elements/oneMKL/source/domains/blas/scal.rst
This PR is adding half/bfloat16 support for select L1 routines: nrm2, dot, axpy, rot, scal.
This is a request from DPCT (Data Parallel Compatibility Tool).
> [oneMKL] [BLAS] Add half/bfloat16 support for select L1 APIs

- source/elements/oneMKL/source/domains/blas/syr2k.rst
In `syr2k`, the description  of the size of the `b` matrix and its leading dimension did not give sense given the (correct) mathematical description of the mathematical operation performed. This PR fixes the inconsistency.
> Fix syr2k b and ldb description in spec.

- scripts/oneapi.py
- source/architecture.rst
- source/conf/common_conf.py
- source/elements/dpcpp/source/index.rst
- source/elements/element_list.rst
- source/elements/sycl/source/conf.py
- source/elements/sycl/source/index.rst
- source/index.rst
* Rename the component from "DPC++" to "SYCL".  We no longer use the name "DPC++" to refer to a specification in its own right.  Instead, "DPC++" refers to an implementation of the SYCL spec.
* Simplify the description of the SYCL component to state that this component includes the SYCL 2020 specification and a specific list of extensions.
* Update the list of extensions to match the "supported" extensions in the DPC++ 2022.2 compiler release.  Use tags in URLs, so the extension pointers are stable for the oneAPI spec.
> Update SYCL component for oneAPI 1.2 release

- source/elements/oneTBB/source/task_scheduler/scheduling_controls/resumable_tasks.rst
Added a requirement on the place where user-specified callable of oneapi::tbb::task::suspend should be called.
Signed-off-by: pavelkumbrasev <pavel.kumbrasev@intel.com>
> Additional requirement for user-specified callable of oneapi::tbb::task::suspend

- source/elements/oneMKL/source/domains/blas/gemm.rst
- source/elements/oneMKL/source/domains/blas/gemm_batch.rst
- source/elements/oneMKL/source/domains/blas/rot.rst
This PR updates the precision support tables for `gemm`, `gemm_batch`, and `rot` BLAS routines with newly supported precisions.
> [oneMKL-BLAS] Update precision support for gemm, gemm batch, rot

- source/elements/oneMKL/source/domains/lapack/getrs_batch.rst
- source/elements/oneMKL/source/domains/lapack/getrs_batch_scratchpad_size.rst
For functions with a stride_b input (GETRS batch strided for USM and BUFFER API), the stride_b description is missing, and the description of stride_a refers to the B matrices instead of the A matrices.
> Fix stride_{a,b} descriptions in getrs_batch functionality in LAPACK domain of oneMKL

- source/elements/oneTBB/source/flow_graph/examples/lightweight_policy.cpp
- source/elements/oneTBB/source/flow_graph/functional_node_policies.rst
Lightweight policy imposes `noexcept` requirement on a function call `operator()` of its node's body.
This patch adds missing description and updates corresponding example.
Notify: @alexey-katranov @vlserov 
Signed-off-by: Fedotov, Aleksei <aleksei.fedotov@intel.com>
> Clarify lightweight policy requirements

- source/elements/oneDPL/source/parallel_api.rst
> [oneDPL] Add base() method to iterator adaptors

- source/conf/common_conf.py
I tried to add the custom latex commands in common_conf.py, however, it still does not render properly in html build. Any idea?
Though it works with the same variables setting when building the oneDNN component spec only
> [DO NOT MERGE] Fix rendering of custom latex commands in html spec

- source/elements/oneMKL/source/domains/lapack/lapack.rst
- source/elements/oneMKL/source/domains/matrix-storage.rst
This addresses #470 by specifying that LAPACK routines require column major storage. The clarification is added to both the main LAPACK page (https://spec.oneapi.io/versions/1.2-rev-1/elements/oneMKL/source/domains/lapack/lapack.html) and the matrix storage page (https://spec.oneapi.io/versions/1.2-rev-1/elements/oneMKL/source/domains/matrix-storage.html).
Note that the links are to the current 1.2 revision of the specification.
> [oneMKL][LAPACK] Clarify that LAPACK routines require column major storage

- source/elements/oneMKL/source/domains/blas/symv.rst
- source/elements/oneMKL/source/domains/blas/syr.rst
- source/elements/oneMKL/source/domains/blas/syr2.rst
This PR updates the spec to include complex versions of `syr`, `syr2`, and `symv`.
> [oneMKL][BLAS] Add complex versions of syr, syr2, symv

- source/elements/oneMKL/source/domains/blas/axpy_batch.rst
- source/elements/oneMKL/source/domains/blas/copy_batch.rst
- source/elements/oneMKL/source/domains/blas/gbmv.rst
- source/elements/oneMKL/source/domains/blas/gemv.rst
- source/elements/oneMKL/source/domains/blas/gemv_batch.rst
- source/elements/oneMKL/source/domains/blas/ger.rst
- source/elements/oneMKL/source/domains/blas/gerc.rst
- source/elements/oneMKL/source/domains/blas/geru.rst
- source/elements/oneMKL/source/domains/blas/hbmv.rst
- source/elements/oneMKL/source/domains/blas/hemv.rst
- source/elements/oneMKL/source/domains/blas/her.rst
- source/elements/oneMKL/source/domains/blas/her2.rst
- source/elements/oneMKL/source/domains/blas/hpmv.rst
- source/elements/oneMKL/source/domains/blas/hpr.rst
- source/elements/oneMKL/source/domains/blas/hpr2.rst
- source/elements/oneMKL/source/domains/blas/sbmv.rst
- source/elements/oneMKL/source/domains/blas/spmv.rst
- source/elements/oneMKL/source/domains/blas/spr.rst
- source/elements/oneMKL/source/domains/blas/spr2.rst
- source/elements/oneMKL/source/domains/blas/symv.rst
- source/elements/oneMKL/source/domains/blas/syr.rst
- source/elements/oneMKL/source/domains/blas/syr2.rst
- source/elements/oneMKL/source/domains/blas/tbmv.rst
- source/elements/oneMKL/source/domains/blas/tbsv.rst
- source/elements/oneMKL/source/domains/blas/tpmv.rst
- source/elements/oneMKL/source/domains/blas/tpsv.rst
- source/elements/oneMKL/source/domains/blas/trmv.rst
- source/elements/oneMKL/source/domains/blas/trsv.rst
This PR clarifies and makes more consistent the descriptions of the `incx` and `incy` parameters (and a couple stride parameters in batch functions).
> [oneMKL][BLAS] make incx, incy argument descriptions in Level 2 BLAS consistent

- source/elements/oneVPL/include/vpl/mfxdefs.h
Unfortunately, GCC does not define `__ILP32__` on 32 bit ARM (contrary to e.g. x86), so rely on `__arm__` instead.
This does not change API/ABI, but fixes a compilation error for one specific architecture and compiler combination.
Avoids broken workarounds in every downstream user of mfxdefs.h,  e.g.:  
https://github.com/oneapi-src/oneVPL/commit/6182082a12#diff-1e7de1ae2d05   https://github.com/intel/cartwheel-ffmpeg/issues/215
> Fix ILP32 data model detection with GCC on 32bit ARM

- source/elements/oneMKL/source/domains/blas/iamax.rst
- source/elements/oneMKL/source/domains/blas/iamin.rst
Adds optional index_base parameter so iamax and iamin can return 1-based indices if user desires.
> [BLAS] add optional index_base parameter to iamax, iamin

- source/elements/oneMKL/source/domains/dft/descriptor.rst
* Relates to https://github.com/oneapi-src/oneAPI-spec/issues/487
* Adds move constructor/assignment to descriptor class
* Otherwise implicitly deleted.
* Add explicit copy constructor/assignment to descriptor class
* Otherwise ambigiuous
* Notes that copy operation is by value.
> [oneMKL] dft::descriptor copy and move (#487)

- source/elements/oneMKL/source/domains/spblas/gemm.rst
- source/elements/oneMKL/source/domains/spblas/gemv.rst
- source/elements/oneMKL/source/domains/spblas/gemvoptimize.rst
- source/elements/oneMKL/source/domains/spblas/matrixinit.rst
- source/elements/oneMKL/source/domains/spblas/releasematrixhandle.rst
- source/elements/oneMKL/source/domains/spblas/setcsrstructure.rst
- source/elements/oneMKL/source/domains/spblas/trmvoptimize.rst
- source/elements/oneMKL/source/domains/spblas/trsvoptimize.rst
**Goal:**
As `oneapi::mkl::sparse` domain has been evolving, we find out that we need to update the oneapi spec for some routines in oneMKL/spblas domain.
**Details:**
In this PR, I've updated several things:
- fixed some minor typos, which is added `const` keyword incorrectly to the output parameter.
- added asynchronous execution support for `set_csr_data` and `release_matrix_handle` routines.
- for `optimize_{gemv, trmv, trsv} routines, combined the separate APIs for `sycl::buffer` and `USM` containers into one common API.
> [oneMKL][spblas] update the spec for several spblas routines

- source/elements/oneMKL/source/domains/stats/onemkl_stats_dataset.rst
- source/elements/oneMKL/source/domains/stats/onemkl_stats_usage_model.rst
* Simplify examples and make them pseudocode
* Remove unnecessary details about dataset
> [oneMKL][Stats][Spec] Simplify and clean up Summary Statistics domain

- source/elements/oneDPL/source/parallel_api.rst
The oneDPL specification seemingly uses early/preliminary variants of SYCL APIs that were changed in SYCL 2020. This patch changes it to the proper SYCL 2020 API.
I think this should be treated as a bug fix in the specification, and not an API modification.
> Update oneDPL specification to align with SYCL 2020 API

- source/elements/oneDPL/source/sycl_kernels_api.rst
The "extensions section" with description of main differences between C++ std. RNG and oneDPL std. RNG has been added to oneAPI specification
> [oneDPL][RNG][Spec] Added the extensions sections

- source/elements/oneMKL/source/domains/spblas/gemvdot.rst
- source/elements/oneMKL/source/domains/spblas/symv.rst
- source/elements/oneMKL/source/domains/spblas/trmv.rst
- source/elements/oneMKL/source/domains/spblas/trsv.rst
**Goal:**
In this PR, I'd like to update some missing `const` keyword for constant parameters within the spec for `spblas` domain in order to achieve consistency in the spec, and fix some minor information.
**Details:**
- add some missing `const` keyword for constant parameters (e.g. `alpha` and `beta`) in the APIs.
- add `const` keyword for input vector/matrix in some spblas APIs.
- remove `y` vector from the input list of `sparse::trsv()` API spec, since `y` is not an input for `sparse::trsv()` API.
> [oneMKL][spblas] add missing 'const' keyword for alpha, beta, and input array, and remove 'y' from input list in sparse::trsv() spec.

- source/elements/oneMKL/source/domains/spblas/gemmoptimize.rst
- source/elements/oneMKL/source/domains/spblas/spblas.rst
- source/elements/oneMKL/source/domains/spblas/symvoptimize.rst
**Goal:**
In this PR, I'd like to add two optimization routines, `optimize_symv()` and `optimize_gemm()` into oneMKL specification.
**Details:**
- Add `optimize_symv()` API into oneMKL specification, which prepares optimization for `oneapi::mkl::sparse::symv()` API.
- Add `optimize_gemm()` API into oneMKL specification, which prepares optimization for `oneapi::mkl::sparse::gemm()` API.
- For `optimize_gemm()` API, we propose two different routines; the first API will prepare optimization based on sparse input matrix only, and the other API will prepare optimization based on both sparse and dense input matrices.
- Add those two APIs in the `Sparse BLAS` main page.
> [oneMKL][spblas] Add `optimize_symv()` and `optimize_gemm()` routines in oneMKL specification.

- source/elements/oneDNN/include/dnnl_graph.hpp
We has aligned the public spec with oneDNN v3.2 public release before in [PR486](https://github.com/oneapi-src/oneAPI-spec/pull/486), but we missed corresponding changes in dnnl_graph.hpp, now we want to fix it.
> [oneDNN Graph] align with oneDNN v3.2 public release in dnnl_graph.hpp

- source/elements/oneMKL/source/domains/spblas/matrixinit.rst
- source/elements/oneMKL/source/domains/spblas/releasematrixhandle.rst
* Change the `oneapi::mkl::sparse::init_matrix_handle()` API to also include a `sycl::queue &queue` as a function argument.
* We recommend this change should go into the finalized version 1.3 release of the oneAPI Specification.
* The rationale is that in implementations of the oneMKL specification, such as [oneMKL Interfaces](https://github.com/oneapi-src/oneMKL/) repository, dispatching directly to a backend library from the spec APIs is easier when the `queue` is part of the API for 
* Without the `queue` in there, implementations need to maintain an implementation of `oneapi::mkl::sparse::matrix_handle_t`.
* With the `queue` in there, implementations can directly forward the arguments to different backend implementations such as the Intel oneMKL library or the cuSPARSE library.
* Also …
> [oneMKL][Sparse BLAS] Add `sycl::queue &` to `sparse::init_matrix_handle()` API

- source/elements/oneCCL/source/spec/collective_operations.rst
Update collective_operations.rst with the info about point-to-point operations.
> [oneCCL] Document point-to-point operations

- source/elements/oneMKL/source/domains/dft/config_params/workspace_placement.rst
- source/elements/oneMKL/source/domains/dft/descriptor.rst
- source/elements/oneMKL/source/domains/dft/enums_and_config_params.rst
This PR is paired with https://github.com/oneapi-src/oneAPI-spec/issues/508, and introduces external workspaces to the oneMKL DFT specification.
* Add support for external workspaces
* Add the following config_params:
* WORKSPACE_PLACEMENT
* WORKSPACE_EXTERNAL_BYTES_REQUIRED
* Add descriptor::set_workspace
* Describe typical usage of an external workspace
> [oneMKL][DFT] Specification for external workspaces for DFTs

- source/elements/oneMKL/source/domains/blas/trmm.rst
- source/elements/oneMKL/source/domains/blas/trsm.rst
This PR adds out-of-place TRMM and TRSM APIs to the spec. As an example, the new TRMM API supports operations of the form $C = \alpha AB + \beta C$, with a similar change for TRSM.
> [oneMKL][BLAS] add out-of-place TRMM and TRSM

- source/elements/oneMKL/source/domains/spblas/trsv.rst
**Goal:**
In this PR, I'd like to update oneMKL specification for `oneapi::mkl::sparse::trsv()` routine to add `alpha` parameter, which is supported by many libraries.
**Details:**
- Update specification by adding `alpha` parameter into `oneapi::mkl::sparse::trsv()` routine.
- Also rename `transpose_val` parameter as `opA`.
- Fix minor typos, e.g. adding `,` after some parameter names.
** Build **
Locally tested to build the change, and it builds successfully and renders well.
> [oneMKL][SpBLAS] Update spec for oneapi::mkl::sparse::trsv() routine to add alpha parameter.

- source/elements/oneMKL/source/domains/rng/device_api/device-rng-mcg31m1.rst
- source/elements/oneMKL/source/domains/rng/device_api/device-rng-mcg59.rst
It doesn't make sense to keep constructors with `std::initializer_list` for `mcg31m1` and `mcg59` generators since one `seed` value is enough. Due to size of the state for `mcg31m1` uint32_t is enough to store it. For `mcg59` uint64_t is enough. So, let's keep only `std::uint32_t seed` for `mcg31m1` and `std::uint64_t seed` for `mcg59`.
Feel free to provide your feedback.
> [oneMKL][RNG] Fixed some bugs for oneMKL RNG device API 

- source/elements/oneMKL/source/domains/dft/compute_backward.rst
- source/elements/oneMKL/source/domains/dft/compute_forward.rst
* The compute_*ward real-real implace overload can be selected when the user intends to use the complex-complex out-of-place overload.
* This suggestion stops this from happening when the user uses non-float arguments that are presumably intended for the complex-complex overload.
For a complete description of the issue, see https://github.com/oneapi-src/oneMKL/issues/499, and also PR with this change to the spec adopted at https://github.com/oneapi-src/oneMKL/pull/503.
> [DFT] Constrain data_type in compute_*ward real-real inplace

- source/elements/oneDPL/source/parallel_api.rst
(Edited by @akukanov)
This patch fixes what we consider to be a bug in the oneDPL specification, namely - the predefined `dpcpp_default` execution policy not being `const`.
Since all explicitly specified member functions of the `device_policy` class are `const`, a mutable policy object differs from a non-mutable (`const`) policy object in two ways:
- when an lvalue, it can be a target to assign (i.e. copy or move) another policy object to, changing the associated SYCL queue to the queue associated with the other policy;
- when an rvalue, it can be moved to another policy object, which may invalidate the associated queue and leave the moved-from policy in an unspecified state.
Neither of the above is an appropriate modification for `dpcpp_default`, potentially changing its semantics as a …
> [oneDPL] Declare predefined `dpcpp_default` policy as `const`

- source/elements/oneDPL/source/sycl_kernels_api.rst
Comparison operators and input/output ones were added for engines and distributions
> [oneDPL][RNG] Removed note about limitations of operators <<,>>, !=, ==

- source/elements/oneDPL/source/common.rst
- source/elements/oneDPL/source/parallel_api.rst
- source/elements/oneDPL/source/parallel_api/execution_policies.rst
- source/elements/oneDPL/source/sycl_kernels_api.rst
Change `:code:` to double backquotes. Apply "Title Case" to headings.
Co-authored-by: dylan.benito@intel.com (@dcbenito)
The patch contains no substantial changes to the content, so according to https://github.com/uxlfoundation/uxl_operational_procedures/blob/release/Process_Documents/Organization_Operational_Process.md#review--approval-process the 0-day review period applies.
> [oneDPL] Formatting modifications

- source/elements/oneDPL/source/parallel_api.rst
- source/elements/oneDPL/source/parallel_api/buffer_wrappers.rst
Continue restructuring the oneDPL specification into smaller pages. This patch splits off the description for buffer wrappers.
The content is unchanged, so the 0-day review period applies (https://github.com/uxlfoundation/uxl_operational_procedures/blob/release/Process_Documents/Organization_Operational_Process.md#review--approval-process).
> [oneDPL] Create a dedicated page for buffer wrappers

- source/elements/oneMKL/source/domains/rng/host_api/mkl-rng-gaussian_mv.rst
- source/elements/oneMKL/source/domains/rng/host_api/mkl-rng-multinomial.rst
- source/elements/oneMKL/source/domains/rng/host_api/mkl-rng-poisson_v.rst
It was found that it's not necessary to make implementors use `std::vector` as a parameter type for `gaussian_mv`, `multinomial`, `poisson_v` distributions. They can also use `std::array` or `std::view` for example to pass data to distribution. This PR relaxes requirement for such parameter types.
Feel free to share your feedback
> [oneMKL][RNG] Extend parameter type for random distributions

- source/elements/oneMKL/source/domains/rng/device_api/device-rng-bernoulli.rst
New supported types for Bernoulli distr have been added
> [RNG] Updating device-rng-bernoulli.rst on small types support

- source/elements/oneDPL/source/parallel_api.rst
Proposing `oneapi::dpl::transform_if` specification for oneDPL.
> [oneDPL] Transform_if APIs

- source/elements/oneDPL/source/parallel_api.rst
This PR aims to improve the specification of `permutation_iterator`, `zip_iterator`, and `transform_iterator` by adding requirements for their source iterator types.  
The source iterator type for each of these iterators share the same requirements, for which a name requirement `ValidParallelIteratorSource` has been defined.  There may be a better or more concise name for this requirement.
`permutation_iterator` has a type `IndexMap` which has a modified set of requirements from `ValidParallelIteratorSource`, because some types like `zip_iterator` and `discard_iterator` do not make sense in this setting. Additionally, `IndexMap` can instead be a functor which transforms consecutive indices into a map.  In practice, one implementation of this functionality would be to use a …
> [oneDPL] Improve requirements for iterator source types

- source/elements/oneMKL/source/domains/rng/device_api/device-rng-uniform-discrete.rst
Uniform distribution can support `std::int64_t`, `std::uint64_t` also.
Feel free to provide your feedback.
> [oneMKL][RNG] Add integer 64-bit support for uniform distribution

- source/elements/oneDPL/source/parallel_api.rst
Proposing `oneapi::dpl::sort_by_key` and `oneapi::dpl::stable_sort_by_key` specification for oneDPL.
> [oneDPL] Sort By Key APIs

- source/elements/oneDPL/source/parallel_api.rst
Proposing oneapi::dpl::histogram specification for oneDPL.
Version 1a from discussion.
> [oneDPL] Add Histogram API

- source/elements/oneMKL/source/domains/spblas/operations/spmm.rst
- source/elements/oneMKL/source/domains/spblas/operations/spmv.rst
- source/elements/oneMKL/source/domains/spblas/operations/spsv.rst
Explicitly require the same memory kind of `alpha` and `beta` parameters. Intel oneMKL Product backends require them to be both on the host. [cuSPARSE](https://docs.nvidia.com/cuda/cusparse/index.html#cusparsesetpointermode) and [rocSPARSE](https://rocm.docs.amd.com/projects/rocSPARSE/en/latest/reference/auxiliary.html#rocsparse-set-pointer-mode) backends use a `set_pointer_mode` function which globally set which kind of memory can be used for all the operations thus it is impossible to use different memory kind for these parameters by design.
> [oneMKL][spblas] Require same memory kind for alpha and beta parameters

- source/elements/oneMKL/source/domains/spblas/data_types/set_coo_matrix_data.rst
- source/elements/oneMKL/source/domains/spblas/data_types/set_csr_matrix_data.rst
- source/elements/oneMKL/source/domains/spblas/data_types/set_dense_matrix_data.rst
- source/elements/oneMKL/source/domains/spblas/data_types/set_dense_vector_data.rst
- source/elements/oneMKL/source/domains/spblas/matrix_view.rst
- source/elements/oneMKL/source/domains/spblas/operations/spmm.rst
- source/elements/oneMKL/source/domains/spblas/operations/spmv.rst
- source/elements/oneMKL/source/domains/spblas/operations/spsv.rst
Update sparse specification to avoid features that are not supported by Intel oneMKL, cuSPARSE or rocSPARSE.
This is used in https://github.com/oneapi-src/oneMKL/pull/500
- Do not allow to change the sparse handle types as no backend support it currently.
- Change the restrictions on matrix view to avoid configurations that are not supported by any backend currently.
- Simplify constructor of matrix_view as the diagonal view is not useful currently. This could cause confusion.
- Do not allow spmv conjtrans with symmetric or Hermitian matrices
> [oneMKL][spblas] Restrict features not supported by any backends

- source/elements/oneDPL/source/parallel_api/execution_policies.rst
This PR describes oneDPL `is_execution_policy` trait in more detail, and also addresses https://github.com/uxlfoundation/oneAPI-spec/issues/558.
> [oneDPL] Create a subsection for is_execution_policy type trait

- source/elements/oneDPL/source/parallel_api/buffer_wrappers.rst
The patch updates the description for buffer wrappers (`dpl::begin/end` function) to clarify the semantics of the type they return.
It also addresses https://github.com/uxlfoundation/oneAPI-spec/issues/482
> [oneDPL] Clarify the semantics of dpl::begin/end return type

- source/elements/oneTBB/source/configuration/version_information.rst
- source/elements/oneTBB/source/index.rst
- source/elements/oneTBB/source/nested-index.rst
The patch also modifies the wording for the ``TBB_INTERFACE_VERSION`` macro, to align with the newly added one and be somewhat more accurate.
> [oneTBB] Add specification version macro

- source/elements/oneDPL/source/parallel_api/execution_policies.rst
Addresses #271.
For this patch, I believe the 7 days review period [applies](https://github.com/uxlfoundation/uxl_operational_procedures/blob/release/Process_Documents/Organization_Operational_Process.md#review--approval-process):
> 7 days for major changes to non-API modifications (such as changes to the documentation of an API)
> [oneDPL] Specify copy and move semantics for device_policy

- source/elements/oneMKL/source/domains/dft/compute_backward.rst
- source/elements/oneMKL/source/domains/dft/compute_forward.rst
- source/elements/oneMKL/source/domains/dft/config_params/data_layouts.rst
- source/elements/oneMKL/source/domains/dft/config_params/storage_formats.rst
- source/elements/oneMKL/source/domains/dft/config_params/workspace_placement.rst
- source/elements/oneMKL/source/domains/dft/descriptor.rst
- source/elements/oneMKL/source/domains/dft/dft.rst
- source/elements/oneMKL/source/domains/dft/enums_and_config_params.rst
The suggested changes are split in two main commits:
- 479026665d1e85b592176ee941c3bfff0ae7860c does not introduce any major changes to the _content_ of the specification pages for oneMKL DFT but improves many aspects: typos fixed, some corrections, unifying usage of inline literals and improving consistency thereof, etc. (full details available in the commit's message);
- 4b3a48f86bbfed8565627a2af67316b8828cc6bc introduces content-modifying changes targeting:
- the resolution of current inconsistencies in the specs regarding the specified types for some configuration values and the usage of the ``set_value`` and ``get_value`` variadic member functions (simply _cannot_ be implemented as is);
-  the improvement of (type-)safety for the configuration-setting and configuration-querying …
> [oneMKL, DFT] Suggested changes for oneMKL DFT APIs (typo fixes, corrections, revisions, and type-safety-motivated changes)

- source/elements/oneMKL/source/domains/spblas/data_types/set_matrix_property.rst
- source/elements/oneMKL/source/domains/spblas/operations/spmm.rst
- source/elements/oneMKL/source/domains/spblas/operations/spmv.rst
- source/elements/oneMKL/source/domains/spblas/operations/spsv.rst
Following the discussion in https://github.com/oneapi-src/oneMKL/pull/527#discussion_r1666587321 I suggest to introduce the `sorted_by_rows` property.
Note that this [section](https://github.com/uxlfoundation/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/spblas/data_types/format-descriptions.rst?plain=1#L29) already specifies that the default state of COO format is unsorted.
See compiled html page: [html.zip](https://github.com/user-attachments/files/17101211/html.zip)
> [oneMKL][spblas] Add sorted_by_rows property

- source/index.rst
Fixes the other issue mentioned in https://github.com/uxlfoundation/oneAPI-spec/issues/588
https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-provisional-rev-1/elements/onemkl/source/domains/spblas/data_types/data_handles# does not show the children pages under "Data handles" in the left tree. This change addresses that.
Html build: [docs.zip](https://github.com/user-attachments/files/17476880/docs.zip)
> Increase max tree depth to 4

- source/elements/oneMKL/source/architecture/api_design.inc.rst
Addressing https://github.com/uxlfoundation/oneAPI-spec/issues/577. Details are there
> [onrMKL] Add Summary Statisitics domain into api_design.inc.rst

- source/elements/oneMKL/source/domains/lapack/getri.rst
- source/elements/oneMKL/source/domains/lapack/getri_batch.rst
- source/elements/oneMKL/source/domains/lapack/getrs.rst
- source/elements/oneMKL/source/domains/lapack/getrs_batch.rst
- source/elements/oneMKL/source/domains/lapack/orgbr.rst
- source/elements/oneMKL/source/domains/lapack/orgqr.rst
- source/elements/oneMKL/source/domains/lapack/orgqr_batch.rst
- source/elements/oneMKL/source/domains/lapack/orgtr.rst
- source/elements/oneMKL/source/domains/lapack/ormqr.rst
- source/elements/oneMKL/source/domains/lapack/ormrq.rst
- source/elements/oneMKL/source/domains/lapack/ormtr.rst
- source/elements/oneMKL/source/domains/lapack/potrs.rst
- source/elements/oneMKL/source/domains/lapack/potrs_batch.rst
- source/elements/oneMKL/source/domains/lapack/trtrs.rst
- source/elements/oneMKL/source/domains/lapack/ungbr.rst
- source/elements/oneMKL/source/domains/lapack/ungqr.rst
- source/elements/oneMKL/source/domains/lapack/ungqr_batch.rst
- source/elements/oneMKL/source/domains/lapack/ungtr.rst
- source/elements/oneMKL/source/domains/lapack/unmqr.rst
- source/elements/oneMKL/source/domains/lapack/unmrq.rst
- source/elements/oneMKL/source/domains/lapack/unmtr.rst
Input matrices should be const qualified for clarity.
> [oneMKL][LAPACK] Const-qualify USM pointers for input matrices

- source/elements/oneMKL/source/domains/lapack/ormtr.rst
- source/elements/oneMKL/source/domains/lapack/ormtr_scratchpad_size.rst
- source/elements/oneMKL/source/domains/lapack/unmtr.rst
- source/elements/oneMKL/source/domains/lapack/unmtr_scratchpad_size.rst
For ormtr and unmtr, the specification incorrectly specifies that LDC must be >= max(1,n), when in fact it should be >= max(1,m).
This was done for all {or,un}mtr related APIs (buffer, USM, and scratchpad size).
Also changed notation in these files to ld* >= x instead of x <= ld*.
Fixed an issue where the first row of the input parameters table had been bolded (incorrectly considered a header row) and added missing table to unmtr_scratchpad_size.
> [oneMKL][LAPACK] Fix ldc size requirements in {or,un}mtr related files

- source/elements/oneMath/source/architecture/other_architecture.inc.rst
When using a definition check,
```c
#ifdef ONEMATH_BLAS_SPEC_VERSION
```
a preprocessor may evaluate an undefined macro to `0`. This means that the existing `000` version for non-compliance is equivalent to the macro not being defined at all and yields the same result for `#ifdef`.
To enable the check for definition of the macro itself, meaning, provide different outputs for:
```c
#define ONEMATH_BLAS_SPEC_VERSION 0   // domain non-compliant with specification
```
case and
```c
// #define ONEMATH_BLAS_SPEC_VERSION   // missing macro definition, may be 0
```
case, we need to use a number other than `0`. `001` is hence proposed as the non-compliance version. It does not conflict with any existing release of the specification. As a natural extension, versions between `001` and `100`(Spec …
> Update non-compliance version to allow definition checks

- source/elements/oneMath/source/domains/rng/device_api/device-distributions-template-parameter-method.rst
- source/elements/oneMath/source/domains/rng/device_api/device-distributions.rst
- source/elements/oneMath/source/domains/rng/device_api/device-rng-geometric.rst
Proposal to add [geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution) to oneMath RNG Device API.
Overview: API similar to existing Bernoulli distribution. Supported data types: 32 and 64 integer types.
_fix:_ changed notes style for RNG
> [oneMath][RNG] Add geometric distribution to Device API

- source/elements/oneTBB/source/task_scheduler/task_arena/task_scheduler_observer_cls.rst
Remove the mentions of global usage of task_scheduler_observer.
> [oneTBB] Update task_scheduler_observer_cls.rst

- source/elements/oneMath/source/domains/rng/device_api/device-rng-uniform-discrete.rst
Since (u)int8 and (u)int16 types support was added to Uniform at the DPNP request
> [oneMath][RNG] Updated supported types for Discrete Uniform

- source/elements/oneMath/source/domains/rng/host_api/engines-basic-random-number-generators.rst
- source/elements/oneMath/source/domains/rng/host_api/onemath-rng-mt2203.rst
In general, the amount of Mersenne Twister pseudorandom number generators mustn't be specified as concrete number. Implementors need to have freedom in terms of how much Mersenne Twister generators to use
> [oneMath][RNG] Make number of generators for MT2203 be implementation defined

- source/elements/oneDPL/source/parallel_api/parallel_range_api.rst
Another oversight found in the signatures of range algorithms: `std::projected_value_t` requires C++26.
To overcome the issue, it is replaced with an analogous alias added only for exposition (i.e., not as a public API) and defined in terms of C++20.
For comparison, this is the standard definition of `std::projected_value_t`:
```c++
template<indirectly_readable I, indirectly_regular_unary_invocable<I> Proj>
using projected_value_t = // freestanding
remove_cvref_t<invoke_result_t<Proj&, iter_value_t<I>&>>;
```
It's a backward-compatible bug fix. Ideally it should be added to a revision of the specification v1.4.
> [oneDPL] Fix the function signatures to not require std::projected_value_t

- source/elements/oneDPL/source/parallel_api/execution_policies.rst
- source/elements/oneDPL/source/parallel_api/iterators.rst
Specification for "indirectly device accessible iterator" customization point and public trait.  Based upon proposed [RFC].(https://github.com/uxlfoundation/oneDPL/pull/1999)
> [oneDPL] Indirectly Device Accessible Iterator Customization Point and Public Trait

- source/elements/oneDPL/source/parallel_api/iterators.rst
From the suggestion [here](https://github.com/uxlfoundation/oneAPI-spec/pull/620#discussion_r2074207876), this PR adjust the language around `is_indirectly_device_accessible` slightly.
This is not a semantic change, so if there is consensus, I will not wait the 2 weeks to merge this.
> [oneDPL] Indirectly device accessible minor language adjustment

- source/elements/oneMath/source/domains/rng/bibliography.rst
- source/elements/oneMath/source/domains/rng/device_api/device-engines.rst
- source/elements/oneMath/source/domains/rng/device_api/device-rng-pcg64-dxsm.rst
The PCG is a family of random number generators based on linear congruential generator (LCG). The algorithm applies permutation function to improve statistical properties of LCG.
PCG64 DXSM uses `double xorshift multiply` output function and has a period of 2^128.
Added new page for the engine, modified bibliography and engines overview.
> [oneMath][RNG] Add PCG64 DXSM generator to Device API

- source/elements/oneDPL/source/parallel_api/iterators.rst
A body-less hidden friend can look like a common error for friend functions where one intends to externally define the friend, but omits a forward declaration of a template function and template syntax within the class.  
There is no actual problem with the body-less hidden friend, but to avoid looking like this common trap, lets define a minimal body in this case (which creates a one-to-one mapping with the instances of the template class).
This doesn't change the semantics, only our examples and therefore recommendations for usage.
(g++ warns when it sees something like the example prior to this change)
> [oneDPL] indirectly_device_accessible adjust hidden friend example 

- source/elements/oneMath/source/domains/stats/onemath_stats_central_moment.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_central_moment_user_mean.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_central_sum.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_central_sum_user_mean.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_kurtosis.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_kurtosis_user_mean.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_max.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_mean.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_min.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_min_max.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_raw_moment.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_raw_sum.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_skewness.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_skewness_user_mean.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_variation.rst
- source/elements/oneMath/source/domains/stats/onemath_stats_variation_user_mean.rst
Added a Mathematical Notation rubric with formulae for better readability
> [oneMath][stats] Add formulae to statistic routines

- source/elements/oneDPL/source/parallel_api/parallel_range_api.rst
A small change that clarifies the differences of oneDPL parallel range algorithms with the standard ones. The change is editorial, with no modifications of API semantics.
> [oneDPL] Clarify the differences with C++20 range algorithms

- source/elements/oneDPL/source/parallel_api/parallel_range_api.rst
Adding `reverse`, `swap_ranges` and `unique` parallel range algorithms into oneDPL specification.
> [oneDPL] Add more in-place mutating parallel range aglrithms

- source/elements/oneDPL/source/parallel_api/parallel_range_api.rst
Adding `reverse_copy` and `unique_copy` parallel range algorithms into oneDPL specification.
> [oneDPL] Add more copying mutating parallel range algorithms

- source/elements/oneMath/source/domains/vm/acospi.rst
- source/elements/oneMath/source/domains/vm/atanh.rst
- source/elements/oneMath/source/domains/vm/cbrt.rst
- source/elements/oneMath/source/domains/vm/expm1.rst
- source/elements/oneMath/source/domains/vm/tanpi.rst
ref: [Std C23 Annex F: IEC 60559 floating-point arithmetic (PDF)](https://open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf)
current doc:
- [cbrt — oneAPI Specification 1.4-provisional-rev-1 documentation](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-rev-1/elements/onemath/source/domains/vm/cbrt#onemath-vm-cbrt)
- [acospi — oneAPI Specification 1.4-provisional-rev-1 documentation](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-rev-1/elements/onemath/source/domains/vm/acospi#onemath-vm-acospi)
- [atanh — oneAPI Specification 1.4-provisional-rev-1 documentation](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/v1.4-rev-1/elements/onemath/source/domains/vm/atanh#onemath-vm-atanh)
- [expm1 — oneAPI Specification 1.4-provisional-rev-1 …
> [oneMath][Vector Math] fix typo in Mathematical Functions docs
